spring:
  application:
    name: com.eagle0ey.rabbitmq-demo
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

server:
  port: 8081

rabbitmq:
  exchange:
    requests: exchange.requests
    jsonrequests: exchange.jsonrequests

  queue:
    requests: queue.requests
    jsonrequests: queue.jsonrequests

  route:
    requests: routing_key.requests
    jsonrequests: routing_key.jsonrequests

